//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("pm-kuerten")]
[assembly: AssemblyVersion("5.1.0")]
[assembly: AssemblyFileVersion("5.1.0")]
[assembly: AssemblyInformationalVersion("5.1.0-alpha.671")]
[assembly: AssemblyCopyright("Copyright © pm-kuerten 2014 - 2024")]

